workflows:
  ios-capacitor-build:
    name: iOS Capacitor Build
    max_build_duration: 60
    environment:
      groups:
        - appstore_credentials
      vars:
        APPLE_APP_ID: com.osama.alnoorway
        APPLE_TEAM_ID: "AU27C9M3JX"
        NODE: latest
        XCODE: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
      - name: Sync Capacitor iOS
        script: npx cap sync ios
      - name: Build iOS app
        script: |
          xcodebuild -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            DEVELOPMENT_TEAM=AU27C9M3JX \
            -allowProvisioningUpdates \
            -archivePath $CM_BUILD_DIR/ios/archive.xcarchive \
            archive
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/ios/archive.xcarchive \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath $CM_BUILD_DIR/ios/export
    artifacts:
      - $CM_BUILD_DIR/ios/export/*.ipa
    publishing:
      app_store_connect:
        api_key: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDRHzyzgvjS7E386fivfRTXr3tpxh4ooLxES/c81NXsagCgYIKoZIzj0DAQehRANCAASg2QXMhRhikra8RTw0flB/KLPDjTMK3/uiqznr+bIOVf1rsxE85oT09D9IP2U97SMEo3gs5N/Pp6W6mikBKqFT
        key_id: H7P8AK33H4
        issuer_id: 73f80bdd-1323-4133-a244-3175d8b6b0dd
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
